ci/cd
Signed-off-by: alhussain-meter <alhussain.hayjan@meter.com.sa>

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -3,56 +3,57 @@ name: Develop CI/CD Pipeline
 on:
   push:
     branches:
-        - develop
-        - main
-        - develop-AU
-        - main-AU
-        - develop-UAE
-        - main-UAE
-        - develop-CN
-        - main-CN
-        - uae-dev-update
+      - develop
+      - main
+      - develop-AU
+      - main-AU
+      - develop-UAE
+      - main-UAE
+      - develop-CN
+      - main-CN
+      - uae-dev-update
+
 jobs:
   build:
     runs-on: ubuntu-latest
     permissions: write-all
     steps:
-    - uses: actions/checkout@v4
-    
-    - name: Use Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: '20'
-        cache: 'npm'
-        
-    - name: Install dependencies
-      run: npm ci
-      
-    - name: Build
-      run: npm run build 
-    - name: Delete Old Artifacts
-      uses: actions/github-script@v6
-      id: artifact
-      with:
-        script: |
-          const res = await github.rest.actions.listArtifactsForRepo({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-          })
+      - uses: actions/checkout@v4
 
-          res.data.artifacts
-            .forEach(({ id }) => {
+      - name: Use Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20'
+          cache: 'npm'
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Build
+        run: npm run build
+
+      - name: Delete Old Artifacts
+        uses: actions/github-script@v6
+        id: artifact
+        with:
+          script: |
+            const res = await github.rest.actions.listArtifactsForRepo({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+            });
+            res.data.artifacts.forEach(({ id }) => {
               github.rest.actions.deleteArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: id,
-              })
-            })  
-    - name: Upload artifact
-      uses: actions/upload-artifact@v4
-      with:
-        name: dist
-        path: dist/
+              });
+            });
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: dist
+          path: dist/
 
   docker:
     needs: build
@@ -60,46 +61,45 @@ jobs:
     permissions:
       contents: read
       packages: write
-
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-    
-    - name: Download artifact
-      uses: actions/download-artifact@v4
-      with:
-        name: dist
-        path: dist
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: dist
+          path: dist
+      
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Log in to GitHub Container Registry
-      uses: docker/login-action@v3
-      with:
-        registry: ghcr.io
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Extract metadata
+        id: meta
+        uses: docker/metadata-action@v5
+        with:
+          images: ghcr.io/${{ github.repository }}
 
-    - name: Extract metadata (tags, labels) for Docker
-      id: meta
-      uses: docker/metadata-action@v5
-      with:
-        images: ghcr.io/${{ github.repository }}
-
-    - name: Build and push Docker image
-      uses: docker/build-push-action@v4
-      with:
-        context: .
-        file: ./docker/Dockerfile.${{ github.ref_name }}
-        push: true
-        tags: ${{ steps.meta.outputs.tags }}
-        labels: ${{ steps.meta.outputs.labels }}
+      - name: Build and push image
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          file: ./docker/Dockerfile.${{ github.ref_name }}
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
 
   deploy:
     needs: docker
     runs-on: ubuntu-latest
-    
     steps:
-    - name: Set environment variables per branch
-      run: |
+
+      - name: Set environment variables per branch
+        run: |
           case "${{ github.ref_name }}" in
             develop)
               echo "HOST=${{ secrets.VM_HOST_DEV }}" >> $GITHUB_ENV
@@ -121,10 +121,6 @@ jobs:
               echo "HOST=${{ secrets.VM_HOST_DEV_UAE }}" >> $GITHUB_ENV
               echo "USER=${{ secrets.VM_USER_DEV_UAE }}" >> $GITHUB_ENV
               ;;
-            uae-dev-update)
-              echo "HOST=${{ secrets.VM_HOST_DEV_UP }}" >> $GITHUB_ENV
-              echo "USER=${{ secrets.VM_USER_DEV_UP }}" >> $GITHUB_ENV
-              ;;
             main-UAE)
               echo "HOST=${{ secrets.VM_HOST_MAIN_UAE }}" >> $GITHUB_ENV
               echo "USER=${{ secrets.VM_USER_MAIN_UAE }}" >> $GITHUB_ENV
@@ -137,47 +133,58 @@ jobs:
               echo "HOST=${{ secrets.VM_HOST_MAIN_CN }}" >> $GITHUB_ENV
               echo "USER=${{ secrets.VM_USER_MAIN_CN }}" >> $GITHUB_ENV
               ;;
+            uae-dev-update)
+              echo "HOST=${{ secrets.VM_HOST_DEV_UP }}" >> $GITHUB_ENV
+              echo "USER=${{ secrets.VM_USER_DEV_UP }}" >> $GITHUB_ENV
+              ;;
             *)
               echo "Unsupported branch: ${{ github.ref_name }}"
               exit 1
               ;;
           esac
-    - name: Deploy to VM
-      env:
-        PRIVATE_KEY: ${{ 
-            github.ref_name == 'develop' && secrets.VM_SSH_PRIVATE_KEY_DEV || 
-            github.ref_name == 'main' && secrets.VM_SSH_PRIVATE_KEY_PROD_GCP || 
-            github.ref_name == 'develop-AU' && secrets.VM_SSH_PRIVATE_KEY_DEV_AU || 
-            github.ref_name == 'main-AU' && secrets.VM_SSH_PRIVATE_KEY_MAIN_AU || 
-            github.ref_name == 'develop-UAE' && secrets.VM_SSH_PRIVATE_KEY_DEV_UAE || 
-            github.ref_name == 'uae-dev-update' && secrets.VM_SSH_PRIVATE_KEY_DEV_UP ||
-            github.ref_name == 'main-UAE' && secrets.VM_SSH_PRIVATE_KEY_MAIN_UAE || 
-            github.ref_name == 'develop-CN' && secrets.VM_SSH_PRIVATE_KEY_DEV_CN || 
-            github.ref_name == 'main-CN' && secrets.VM_SSH_PRIVATE_KEY_MAIN_CN }}
 
-      run: |
-        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
-        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
-          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-          REPO_LOWER=$(echo "${{ github.repository }}" | tr "[:upper:]" "[:lower:]")
-          cd /home/${USER}/meter
-          git fetch origin ${{ github.ref_name }}
-          git checkout ${{ github.ref_name }}
-          git pull origin ${{ github.ref_name }}
-          # Create or update .env file
-              cat << EOF > .env
-        GITHUB_REPOSITORY=$REPO_LOWER
-        IMAGE_TAG=${{ github.ref_name }}
-        EOF
-          git pull
-          docker pull ghcr.io/$REPO_LOWER:${{ github.ref_name }}
-          docker compose down  || { echo "Docker Compose down failed"; exit 1; }
-          docker compose up -d || { echo "Docker Compose up failed"; exit 1; }
-          sleep 10
-          if ! docker compose ps | grep -q "Up"; then
-            echo "Containers failed to start properly"
-            docker compose logs
-            exit 1
-          fi
-          echo "Deployment successful"
-        '
+      - name: Deploy to VM
+        env:
+          PRIVATE_KEY: >-
+            ${{ github.ref_name == 'develop' && secrets.VM_SSH_PRIVATE_KEY_DEV ||
+                github.ref_name == 'main' && secrets.VM_SSH_PRIVATE_KEY_PROD_GCP ||
+                github.ref_name == 'develop-AU' && secrets.VM_SSH_PRIVATE_KEY_DEV_AU ||
+                github.ref_name == 'main-AU' && secrets.VM_SSH_PRIVATE_KEY_MAIN_AU ||
+                github.ref_name == 'develop-UAE' && secrets.VM_SSH_PRIVATE_KEY_DEV_UAE ||
+                github.ref_name == 'main-UAE' && secrets.VM_SSH_PRIVATE_KEY_MAIN_UAE ||
+                github.ref_name == 'develop-CN' && secrets.VM_SSH_PRIVATE_KEY_DEV_CN ||
+                github.ref_name == 'main-CN' && secrets.VM_SSH_PRIVATE_KEY_MAIN_CN ||
+                github.ref_name == 'uae-dev-update' && secrets.VM_SSH_PRIVATE_KEY_DEV_UP }}
+        run: |
+          echo "$PRIVATE_KEY" > private_key
+          chmod 600 private_key
+
+          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
+            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+            REPO_LOWER=$(echo "${{ github.repository }}" | tr "[:upper:]" "[:lower:]")
+            
+            cd /home/${USER}/meter
+
+            git fetch origin ${{ github.ref_name }}
+            git checkout ${{ github.ref_name }}
+            git pull origin ${{ github.ref_name }}
+
+            cat << EOF > .env
+          GITHUB_REPOSITORY=$REPO_LOWER
+          IMAGE_TAG=${{ github.ref_name }}
+          EOF
+
+            docker pull ghcr.io/$REPO_LOWER:${{ github.ref_name }}
+            docker compose down || true
+            docker compose up -d
+
+            sleep 10
+
+            if ! docker compose ps | grep -q "Up"; then
+              echo "Containers failed to start properly"
+              docker compose logs
+              exit 1
+            fi
+
+            echo "Deployment successful"
+          '
