Edit deployment

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -84,15 +84,10 @@ jobs:
         ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
           echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
           REPO_LOWER=$(echo "${{ github.repository }}" | tr "[:upper:]" "[:lower:]")
-          cd /home/ubuntu/meter
-          # Create or update .env file
-              cat << EOF > .env
-        GITHUB_REPOSITORY=$REPO_LOWER
-        IMAGE_TAG=${{ github.ref_name }}
-        EOF
+          cd /home/ubuntu/meter-backend
           docker pull ghcr.io/$REPO_LOWER:${{ github.ref_name }}
-          docker compose down || { echo "Docker Compose down failed"; exit 1; }
-          docker compose up -d || { echo "Docker Compose up failed"; exit 1; }
+          docker compose down meter-frontend || { echo "Docker Compose down failed"; exit 1; }
+          docker compose up meter-frontend -d || { echo "Docker Compose up failed"; exit 1; }
           sleep 10
           if ! docker compose ps | grep -q "Up"; then
             echo "Containers failed to start properly"
